### ISSUE TITLE
nice grabber my guy LOL

### ISSUE THREAD

**Issue by socialwtf** [aniko33/NukeLib#5]
![image_2024-04-06_160419464](https://github.com/aniko33/NukeLib/assets/150347013/3a71f6dc-ecf8-4aa4-b350-0d41a2c8b7e8)

**Comment by aniko33** [comment]
It is not a token grabber, it is a library for nuking on discord using the undocumented API. In if file doesn't hold any access to discord paths, doesn't go use DPAPI or AES to do decryption of local storage, and doesn't even have regexes. How can it get your token? So instead of leaving an issues named "nice grabber," read the code and if you are not capable shut up
